In [1]:
import pandas as pd
from sqlalchemy import create_engine
# connection string
engine = create_engine(
    "postgresql+psycopg2://udemy:udemy123@localhost:5434/udemy_master_of_pandas"
)

# read table
employees = pd.read_sql("SELECT * FROM archive.employee_data;", engine)

In [2]:
employees

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,...,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [3]:
employees.columns

Index(['EmpID', 'FirstName', 'LastName', 'StartDate', 'ExitDate', 'Title',
       'Supervisor', 'ADEmail', 'BusinessUnit', 'EmployeeStatus',
       'EmployeeType', 'PayZone', 'EmployeeClassificationType',
       'TerminationType', 'TerminationDescription', 'DepartmentType',
       'Division', 'DOB', 'State', 'JobFunctionDescription', 'GenderCode',
       'LocationCode', 'RaceDesc', 'MaritalDesc', 'Performance Score',
       'Current Employee Rating'],
      dtype='str')

In [4]:
employees.filter(['Title','PayZone'])

                        Title PayZone
0     Production Technician I  Zone C
1     Production Technician I  Zone A
2          Area Sales Manager  Zone B
3          Area Sales Manager  Zone A
4          Area Sales Manager  Zone A
...                       ...     ...
2995  Production Technician I  Zone C
2996  Production Technician I  Zone A
2997  Production Technician I  Zone B
2998  Production Technician I  Zone B
2999  Production Technician I  Zone B

[3000 rows x 2 columns]

In [5]:
employees.filter(['Title','PayZone'] , axis=0)

Empty DataFrame
Columns: [EmpID, FirstName, LastName, StartDate, ExitDate, Title, Supervisor, ADEmail, BusinessUnit, EmployeeStatus, EmployeeType, PayZone, EmployeeClassificationType, TerminationType, TerminationDescription, DepartmentType, Division, DOB, State, JobFunctionDescription, GenderCode, LocationCode, RaceDesc, MaritalDesc, Performance Score, Current Employee Rating]
Index: []

[0 rows x 26 columns]

In [6]:
employees.filter(['Title','PayZone'] , axis=1)

                        Title PayZone
0     Production Technician I  Zone C
1     Production Technician I  Zone A
2          Area Sales Manager  Zone B
3          Area Sales Manager  Zone A
4          Area Sales Manager  Zone A
...                       ...     ...
2995  Production Technician I  Zone C
2996  Production Technician I  Zone A
2997  Production Technician I  Zone B
2998  Production Technician I  Zone B
2999  Production Technician I  Zone B

[3000 rows x 2 columns]

In [7]:
employees.filter([4,2])

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, ...]

[3000 rows x 0 columns]

In [8]:
employees.filter([4,2] , axis=0)

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4

In [10]:
employees.filter(items=[4,2] , axis=0 )

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4

In [11]:
employees.filter(items=['Title','PayZone'] , axis=1)

                        Title PayZone
0     Production Technician I  Zone C
1     Production Technician I  Zone A
2          Area Sales Manager  Zone B
3          Area Sales Manager  Zone A
4          Area Sales Manager  Zone A
...                       ...     ...
2995  Production Technician I  Zone C
2996  Production Technician I  Zone A
2997  Production Technician I  Zone B
2998  Production Technician I  Zone B
2999  Production Technician I  Zone B

[3000 rows x 2 columns]

In [13]:
employees.filter(like='A')

                              ADEmail
0         uriah.bridges@bilearner.com
1           paula.small@bilearner.com
2           edward.buck@bilearner.com
3       michael.riordan@bilearner.com
4         jasmine.onque@bilearner.com
...                               ...
2995    jakobe.erickson@bilearner.com
2996  adyson.strickland@bilearner.com
2997    annabel.wilkins@bilearner.com
2998       kendra.braun@bilearner.com
2999         chace.kerr@bilearner.com

[3000 rows x 1 columns]

In [14]:
employees.filter(like='A' , axis =0)

Empty DataFrame
Columns: [EmpID, FirstName, LastName, StartDate, ExitDate, Title, Supervisor, ADEmail, BusinessUnit, EmployeeStatus, EmployeeType, PayZone, EmployeeClassificationType, TerminationType, TerminationDescription, DepartmentType, Division, DOB, State, JobFunctionDescription, GenderCode, LocationCode, RaceDesc, MaritalDesc, Performance Score, Current Employee Rating]
Index: []

[0 rows x 26 columns]

In [15]:
employees.filter(like='a' , axis =1)

,FirstName,LastName,StartDate,ExitDate,ADEmail,EmployeeStatus,PayZone,EmployeeClassificationType,TerminationType,TerminationDescription,DepartmentType,State,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,Uriah,Bridges,20-Sep-19,NaN,uriah.bridges@bilearner.com,Active,Zone C,Temporary,Unk,NaN,Production,MA,34904,White,Widowed,Fully Meets,4
1,Paula,Small,11-Feb-23,NaN,paula.small@bilearner.com,Active,Zone A,Part-Time,Unk,NaN,Production,MA,6593,Hispanic,Widowed,Fully Meets,3
2,Edward,Buck,10-Dec-18,NaN,edward.buck@bilearner.com,Active,Zone B,Part-Time,Unk,NaN,Sales,MA,2330,Hispanic,Widowed,Fully Meets,4
3,Michael,Riordan,21-Jun-21,NaN,michael.riordan@bilearner.com,Active,Zone A,Full-Time,Unk,NaN,Sales,ND,58782,Other,Single,Fully Meets,2
4,Jasmine,Onque,29-Jun-19,NaN,jasmine.onque@bilearner.com,Active,Zone A,Temporary,Unk,NaN,Sales,FL,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,Jakobe,Erickson,22-Jun-22,07-Aug-22,jakobe.erickson@bilearner.com,Leave of Absence,Zone C,Part-Time,Retirement,In forget fast.,Production,MA,44500,Other,Widowed,Fully Meets,3
2996,Adyson,Strickland,28-Dec-20,NaN,adyson.strickland@bilearner.com,Active,Zone A,Full-Time,Unk,NaN,Production,MA,35444,Black,Widowed,Fully Meets,3
2997,Annabel,Wilkins,09-Dec-20,04-Aug-22,annabel.wilkins@bilearner.com,Voluntarily Terminated,Zone B,Temporary,Involuntary,Smile high bar white spend forget choice near.,Production,MA,6608,White,Single,Fully Meets,2
2998,Kendra,Braun,28-May-19,23-Oct-21,kendra.braun@bilearner.com,Voluntarily Terminated,Zone B,Full-Time,Resignation,Fine expect election either turn.,Production,MA,3807,Hispanic,Divorced,Fully Meets,2
2999,Chace,Kerr,27-Apr-22,NaN,chace.kerr@bilearner.com,Active,Zone B,Temporary,Unk,NaN,Production,MA,57487,White,Married,Fully Meets,2

In [16]:
employees.filter(like='Na' , axis =1)

     FirstName    LastName
0        Uriah     Bridges
1        Paula       Small
2       Edward        Buck
3      Michael     Riordan
4      Jasmine       Onque
...        ...         ...
2995    Jakobe    Erickson
2996    Adyson  Strickland
2997   Annabel     Wilkins
2998    Kendra       Braun
2999     Chace        Kerr

[3000 rows x 2 columns]

In [17]:
employees.filter(like='D' , axis =1)

,EmpID,StartDate,ExitDate,ADEmail,TerminationDescription,DepartmentType,Division,DOB,JobFunctionDescription,RaceDesc,MaritalDesc
0,3427,20-Sep-19,NaN,uriah.bridges@bilearner.com,NaN,Production,Finance & Accounting,07-10-1969,Accounting,White,Widowed
1,3428,11-Feb-23,NaN,paula.small@bilearner.com,NaN,Production,Aerial,30-08-1965,Labor,Hispanic,Widowed
2,3429,10-Dec-18,NaN,edward.buck@bilearner.com,NaN,Sales,General - Sga,06-10-1991,Assistant,Hispanic,Widowed
3,3430,21-Jun-21,NaN,michael.riordan@bilearner.com,NaN,Sales,Finance & Accounting,04-04-1998,Clerk,Other,Single
4,3431,29-Jun-19,NaN,jasmine.onque@bilearner.com,NaN,Sales,General - Con,29-08-1969,Laborer,Other,Married
...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,22-Jun-22,07-Aug-22,jakobe.erickson@bilearner.com,In forget fast.,Production,Engineers,23-06-1998,Model Assistant,Other,Widowed
2996,3423,28-Dec-20,NaN,adyson.strickland@bilearner.com,NaN,Production,Engineers,10-06-2001,Engineer,Black,Widowed
2997,3424,09-Dec-20,04-Aug-22,annabel.wilkins@bilearner.com,Smile high bar white spend forget choice near.,Production,Wireline Construction,27-01-1997,Laborer,White,Single
2998,3425,28-May-19,23-Oct-21,kendra.braun@bilearner.com,Fine expect election either turn.,Production,Aerial,28-05-1954,Foreman,Hispanic,Divorced
2999,3426,27-Apr-22,NaN,chace.kerr@bilearner.com,NaN,Production,Field Operations,11-09-1990,Warehouse Technician,White,Married

In [18]:
employees.filter(regex='^A.*')

                              ADEmail
0         uriah.bridges@bilearner.com
1           paula.small@bilearner.com
2           edward.buck@bilearner.com
3       michael.riordan@bilearner.com
4         jasmine.onque@bilearner.com
...                               ...
2995    jakobe.erickson@bilearner.com
2996  adyson.strickland@bilearner.com
2997    annabel.wilkins@bilearner.com
2998       kendra.braun@bilearner.com
2999         chace.kerr@bilearner.com

[3000 rows x 1 columns]

In [19]:
employees.filter(regex='^B.*')

     BusinessUnit
0            CCDR
1              EW
2              PL
3            CCDR
4             TNS
...           ...
2995          PYZ
2996          SVG
2997          TNS
2998          WBL
2999          BPC

[3000 rows x 1 columns]

In [20]:
employees.filter(regex='^C.*')

      Current Employee Rating
0                           4
1                           3
2                           4
3                           2
4                           3
...                       ...
2995                        3
2996                        3
2997                        2
2998                        2
2999                        2

[3000 rows x 1 columns]

In [21]:
employees.filter(regex='^C.*' , axis=0)

Empty DataFrame
Columns: [EmpID, FirstName, LastName, StartDate, ExitDate, Title, Supervisor, ADEmail, BusinessUnit, EmployeeStatus, EmployeeType, PayZone, EmployeeClassificationType, TerminationType, TerminationDescription, DepartmentType, Division, DOB, State, JobFunctionDescription, GenderCode, LocationCode, RaceDesc, MaritalDesc, Performance Score, Current Employee Rating]
Index: []

[0 rows x 26 columns]

In [22]:
employees.set_index('FirstName',inplace=True)

In [23]:
employees

,EmpID,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,EmployeeType,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
FirstName,,,,,,,,,,,,,,,,,,,,,
Uriah,3427,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,Contract,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
Paula,3428,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,Contract,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
Edward,3429,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,Full-Time,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
Michael,3430,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,Contract,...,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
Jasmine,3431,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,Contract,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Jakobe,3422,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,Part-Time,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
Adyson,3423,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,Part-Time,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
Annabel,3424,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,Contract,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
Kendra,3425,Braun,28-May-19,23-Oct-21,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,Contract,...,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
Chace,3426,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,Full-Time,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [24]:
employees.iloc[99]

EmpID                                                3526
LastName                                           Krause
StartDate                                       15-Sep-22
ExitDate                                              NaN
Title                                  Area Sales Manager
Supervisor                                Paige Flores MD
ADEmail                       darius.krause@bilearner.com
BusinessUnit                                          NEL
EmployeeStatus                                     Active
EmployeeType                                    Full-Time
PayZone                                            Zone B
EmployeeClassificationType                      Full-Time
TerminationType                                       Unk
TerminationDescription                                NaN
DepartmentType                                      Sales
Division                                    General - Con
DOB                                            30-05-1948
State                                                  TX
JobFunctionDescription                            Foreman
GenderCode                                           Male
LocationCode                                        28282
RaceDesc                                            White
MaritalDesc                                       Widowed
Performance Score                             Fully Meets
Current Employee Rating                                 4
Name: Darius, dtype: object

In [30]:
employees.filter(items=['Title'] ,axis=1)

                             Title
FirstName
Uriah      Production Technician I
Paula      Production Technician I
Edward          Area Sales Manager
Michael         Area Sales Manager
Jasmine         Area Sales Manager
...                            ...
Jakobe     Production Technician I
Adyson     Production Technician I
Annabel    Production Technician I
Kendra     Production Technician I
Chace      Production Technician I

[3000 rows x 1 columns]

In [31]:
employees.filter(like='A')

                                   ADEmail
FirstName
Uriah          uriah.bridges@bilearner.com
Paula            paula.small@bilearner.com
Edward           edward.buck@bilearner.com
Michael      michael.riordan@bilearner.com
Jasmine        jasmine.onque@bilearner.com
...                                    ...
Jakobe       jakobe.erickson@bilearner.com
Adyson     adyson.strickland@bilearner.com
Annabel      annabel.wilkins@bilearner.com
Kendra          kendra.braun@bilearner.com
Chace             chace.kerr@bilearner.com

[3000 rows x 1 columns]

In [32]:
employees.filter(like='A' , axis=0)

,EmpID,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,EmployeeType,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
FirstName,,,,,,,,,,,,,,,,,,,,,
Angela,3448,Molina,01-Oct-19,06-Nov-20,Area Sales Manager,Patricia Cook,angela.molina@bilearner.com,SVG,Future Start,Full-Time,...,Engineers,12-05-1958,TX,Specialist,Male,50705,Asian,Widowed,Fully Meets,3
Axel,3456,Howe,06-Mar-23,NaN,Area Sales Manager,Martin Hammond,axel.howe@bilearner.com,NEL,Active,Full-Time,...,Field Operations,25-09-1946,KY,Technician,Female,79623,Black,Divorced,Fully Meets,3
Alisa,3460,James,19-Feb-20,NaN,Area Sales Manager,Dennis Henderson,alisa.james@bilearner.com,SVG,Active,Full-Time,...,Aerial,10-02-1944,TX,Lineman,Male,74682,Asian,Married,Fully Meets,3
Aliana,3462,Nolan,13-Sep-18,17-Sep-21,Area Sales Manager,Brianna Mathews,aliana.nolan@bilearner.com,MSC,Active,Contract,...,Field Operations,09-08-1942,CO,Coordinator,Male,27270,Hispanic,Divorced,Needs Improvement,3
Arely,3474,Patton,09-Mar-20,NaN,Area Sales Manager,Andrew Goodman,arely.patton@bilearner.com,MSC,Active,Full-Time,...,Catv,16-12-1965,CO,Laborer,Male,34481,Other,Divorced,Fully Meets,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Aimee,3383,Hughes,13-Aug-20,02-Oct-20,Production Technician I,Jose Brown,aimee.hughes@bilearner.com,PYZ,Voluntarily Terminated,Part-Time,...,General - Con,01-04-1985,MA,Splicer,Female,20389,Hispanic,Divorced,Exceeds,2
Andrea,3412,Walters,28-Dec-19,NaN,Production Technician II,David Abbott,andrea.walters@bilearner.com,SVG,Active,Part-Time,...,Shop (Fleet),20-03-1991,MA,Mechanic,Female,68155,White,Divorced,Exceeds,3
Aron,3416,Waters,02-Oct-20,NaN,Production Technician I,Amanda Fisher,aron.waters@bilearner.com,BPC,Active,Full-Time,...,Finance & Accounting,18-12-1992,MA,Director,Male,46381,Asian,Married,Fully Meets,2
Adyson,3423,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,Part-Time,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
Annabel,3424,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,Contract,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2

In [33]:
employees.filter(like='Aa' , axis=0)

,EmpID,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,EmployeeType,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
FirstName,,,,,,,,,,,,,,,,,,,,,
Aaron,3541,Weber,06-Apr-20,24-Jul-23,Area Sales Manager,Melanie Garcia,aaron.weber@bilearner.com,SVG,Active,Full-Time,...,Field Operations,27-10-1991,IN,Technician,Male,78938,Black,Married,Exceeds,2
Aaliyah,3783,Watts,09-May-20,NaN,Production Technician I,Jared Whitehead,aaliyah.watts@bilearner.com,EW,Active,Contract,...,Fielders,11-04-1962,MA,Engineer,Male,7773,Asian,Divorced,Fully Meets,3
Aaron,1538,Tapia,20-Jan-23,NaN,Production Technician II,Michael Reed,aaron.tapia@bilearner.com,TNS,Active,Contract,...,Splicing,18-01-2001,MA,Splicer,Male,27010,White,Widowed,Fully Meets,3
Aaden,1808,Mercer,26-Jul-23,NaN,Production Technician I,Victoria Jacobs,aaden.mercer@bilearner.com,EW,Active,Part-Time,...,Splicing,25-09-1983,MA,Coordinator,Female,37289,Black,Married,Fully Meets,3
Aarav,2956,Espinoza,11-Nov-19,NaN,Production Technician I,David Ali,aarav.espinoza@bilearner.com,WBL,Active,Part-Time,...,Engineers,15-12-1999,MA,Project Manager,Male,51029,Hispanic,Widowed,Fully Meets,2

In [35]:
employees.filter(like='a' ,axis=1)

,LastName,StartDate,ExitDate,ADEmail,EmployeeStatus,PayZone,EmployeeClassificationType,TerminationType,TerminationDescription,DepartmentType,State,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
FirstName,,,,,,,,,,,,,,,,
Uriah,Bridges,20-Sep-19,NaN,uriah.bridges@bilearner.com,Active,Zone C,Temporary,Unk,NaN,Production,MA,34904,White,Widowed,Fully Meets,4
Paula,Small,11-Feb-23,NaN,paula.small@bilearner.com,Active,Zone A,Part-Time,Unk,NaN,Production,MA,6593,Hispanic,Widowed,Fully Meets,3
Edward,Buck,10-Dec-18,NaN,edward.buck@bilearner.com,Active,Zone B,Part-Time,Unk,NaN,Sales,MA,2330,Hispanic,Widowed,Fully Meets,4
Michael,Riordan,21-Jun-21,NaN,michael.riordan@bilearner.com,Active,Zone A,Full-Time,Unk,NaN,Sales,ND,58782,Other,Single,Fully Meets,2
Jasmine,Onque,29-Jun-19,NaN,jasmine.onque@bilearner.com,Active,Zone A,Temporary,Unk,NaN,Sales,FL,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Jakobe,Erickson,22-Jun-22,07-Aug-22,jakobe.erickson@bilearner.com,Leave of Absence,Zone C,Part-Time,Retirement,In forget fast.,Production,MA,44500,Other,Widowed,Fully Meets,3
Adyson,Strickland,28-Dec-20,NaN,adyson.strickland@bilearner.com,Active,Zone A,Full-Time,Unk,NaN,Production,MA,35444,Black,Widowed,Fully Meets,3
Annabel,Wilkins,09-Dec-20,04-Aug-22,annabel.wilkins@bilearner.com,Voluntarily Terminated,Zone B,Temporary,Involuntary,Smile high bar white spend forget choice near.,Production,MA,6608,White,Single,Fully Meets,2
Kendra,Braun,28-May-19,23-Oct-21,kendra.braun@bilearner.com,Voluntarily Terminated,Zone B,Full-Time,Resignation,Fine expect election either turn.,Production,MA,3807,Hispanic,Divorced,Fully Meets,2
Chace,Kerr,27-Apr-22,NaN,chace.kerr@bilearner.com,Active,Zone B,Temporary,Unk,NaN,Production,MA,57487,White,Married,Fully Meets,2

In [36]:
employees.filter(regex='^A.*')

                                   ADEmail
FirstName
Uriah          uriah.bridges@bilearner.com
Paula            paula.small@bilearner.com
Edward           edward.buck@bilearner.com
Michael      michael.riordan@bilearner.com
Jasmine        jasmine.onque@bilearner.com
...                                    ...
Jakobe       jakobe.erickson@bilearner.com
Adyson     adyson.strickland@bilearner.com
Annabel      annabel.wilkins@bilearner.com
Kendra          kendra.braun@bilearner.com
Chace             chace.kerr@bilearner.com

[3000 rows x 1 columns]

In [37]:
employees.filter(regex='^A.*' , axis=0)

,EmpID,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,EmployeeType,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
FirstName,,,,,,,,,,,,,,,,,,,,,
Angela,3448,Molina,01-Oct-19,06-Nov-20,Area Sales Manager,Patricia Cook,angela.molina@bilearner.com,SVG,Future Start,Full-Time,...,Engineers,12-05-1958,TX,Specialist,Male,50705,Asian,Widowed,Fully Meets,3
Axel,3456,Howe,06-Mar-23,NaN,Area Sales Manager,Martin Hammond,axel.howe@bilearner.com,NEL,Active,Full-Time,...,Field Operations,25-09-1946,KY,Technician,Female,79623,Black,Divorced,Fully Meets,3
Alisa,3460,James,19-Feb-20,NaN,Area Sales Manager,Dennis Henderson,alisa.james@bilearner.com,SVG,Active,Full-Time,...,Aerial,10-02-1944,TX,Lineman,Male,74682,Asian,Married,Fully Meets,3
Aliana,3462,Nolan,13-Sep-18,17-Sep-21,Area Sales Manager,Brianna Mathews,aliana.nolan@bilearner.com,MSC,Active,Contract,...,Field Operations,09-08-1942,CO,Coordinator,Male,27270,Hispanic,Divorced,Needs Improvement,3
Arely,3474,Patton,09-Mar-20,NaN,Area Sales Manager,Andrew Goodman,arely.patton@bilearner.com,MSC,Active,Full-Time,...,Catv,16-12-1965,CO,Laborer,Male,34481,Other,Divorced,Fully Meets,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Aimee,3383,Hughes,13-Aug-20,02-Oct-20,Production Technician I,Jose Brown,aimee.hughes@bilearner.com,PYZ,Voluntarily Terminated,Part-Time,...,General - Con,01-04-1985,MA,Splicer,Female,20389,Hispanic,Divorced,Exceeds,2
Andrea,3412,Walters,28-Dec-19,NaN,Production Technician II,David Abbott,andrea.walters@bilearner.com,SVG,Active,Part-Time,...,Shop (Fleet),20-03-1991,MA,Mechanic,Female,68155,White,Divorced,Exceeds,3
Aron,3416,Waters,02-Oct-20,NaN,Production Technician I,Amanda Fisher,aron.waters@bilearner.com,BPC,Active,Full-Time,...,Finance & Accounting,18-12-1992,MA,Director,Male,46381,Asian,Married,Fully Meets,2
Adyson,3423,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,Part-Time,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
Annabel,3424,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,Contract,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2

In [38]:
employees.filter(regex='^C.*' , axis=0)

,EmpID,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,EmployeeType,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
FirstName,,,,,,,,,,,,,,,,,,,,,
Carlee,3451,French,18-Feb-21,11-Nov-22,Area Sales Manager,Michael Bradshaw,carlee.french@bilearner.com,TNS,Active,Contract,...,General - Con,15-01-1968,CO,Technician,Male,71071,Other,Divorced,Exceeds,3
Charity,3455,Miranda,29-Jun-21,05-Jul-22,Area Sales Manager,Daniel Rodriguez,charity.miranda@bilearner.com,WBL,Active,Full-Time,...,Project Management - Eng,18-01-1999,KY,Manager,Male,3763,Other,Widowed,Exceeds,4
Cory,3458,Robinson,28-Apr-22,24-May-23,Area Sales Manager,Elizabeth Anderson,cory.robinson@bilearner.com,BPC,Future Start,Contract,...,Field Operations,12-08-1996,TX,Laborer,Female,5194,Hispanic,Single,Needs Improvement,3
Clayton,3466,Walker,13-Apr-22,10-Apr-23,Area Sales Manager,Jon Holden,clayton.walker@bilearner.com,PYZ,Active,Part-Time,...,Aerial,26-01-1979,KY,Supervisor,Male,64288,Other,Married,Exceeds,4
Celia,3467,Curtis,06-May-20,NaN,Area Sales Manager,Michael Odonnell,celia.curtis@bilearner.com,WBL,Active,Contract,...,Fielders,14-05-1987,KY,Engineer,Female,94333,Asian,Divorced,Exceeds,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Catherine,3276,Anthony,25-Jan-21,NaN,Production Technician I,Joshua Lee,catherine.anthony@bilearner.com,CCDR,Active,Contract,...,Engineers,20-11-1996,MA,Project Manager,Male,83059,Asian,Divorced,Fully Meets,2
Cade,3356,Heath,10-Nov-18,NaN,Production Technician I,Marco Stephenson,cade.heath@bilearner.com,PYZ,Active,Full-Time,...,General - Eng,14-08-1991,MA,Technician,Female,34856,Asian,Married,Needs Improvement,3
Cruz,3377,Ashley,24-Feb-20,13-May-23,Production Technician I,Evan Schultz,cruz.ashley@bilearner.com,BPC,Active,Part-Time,...,Splicing,06-09-1989,MA,Foreman,Female,52336,Asian,Widowed,Exceeds,4
Corinne,3399,Reeves,05-Jun-22,01-Jun-23,Production Technician I,Paige Savage,corinne.reeves@bilearner.com,NEL,Active,Full-Time,...,Aerial,25-02-1984,MA,Lineman,Female,16715,White,Widowed,Fully Meets,2
Chace,3426,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,Full-Time,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [39]:
employees.filter(regex='^Ch.*' , axis=0)

,EmpID,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,EmployeeType,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
FirstName,,,,,,,,,,,,,,,,,,,,,
Charity,3455,Miranda,29-Jun-21,05-Jul-22,Area Sales Manager,Daniel Rodriguez,charity.miranda@bilearner.com,WBL,Active,Full-Time,...,Project Management - Eng,18-01-1999,KY,Manager,Male,3763,Other,Widowed,Exceeds,4
Chaim,3473,Mata,29-Jun-23,NaN,Area Sales Manager,Desiree Vang,chaim.mata@bilearner.com,EW,Active,Part-Time,...,Shop (Fleet),01-10-1950,CO,Manager,Male,33379,Hispanic,Widowed,Exceeds,2
Charlie,3476,Koch,12-Jun-23,06-Jul-23,Area Sales Manager,Samantha Cardenas,charlie.koch@bilearner.com,PYZ,Active,Part-Time,...,Fielders,20-06-1945,MA,Engineer,Male,95774,Asian,Divorced,Needs Improvement,2
Chaz,3539,Bruce,08-Dec-19,NaN,Area Sales Manager,John Johnson,chaz.bruce@bilearner.com,BPC,Active,Full-Time,...,General - Con,27-11-1983,CO,Foreman,Male,74448,Hispanic,Single,Fully Meets,5
Charlie,3550,Atkinson,26-Nov-21,14-Oct-22,Area Sales Manager,Jennifer Hicks,charlie.atkinson@bilearner.com,SVG,Future Start,Part-Time,...,Wireline Construction,26-03-1988,TX,Billing,Male,57754,White,Divorced,Fully Meets,1
Charlee,3618,Roth,04-Feb-23,NaN,Production Technician I,Erin Harris,charlee.roth@bilearner.com,MSC,Active,Part-Time,...,Splicing,05-05-1944,MA,Splicer,Male,13186,Black,Married,Fully Meets,3
Chace,3691,Church,23-Nov-20,NaN,Production Technician I,David Valenzuela,chace.church@bilearner.com,TNS,Active,Part-Time,...,Finance & Accounting,03-01-1993,MA,Manager,Male,34316,Asian,Single,Needs Improvement,1
Chaim,3716,Chase,31-Jul-22,18-Feb-23,Production Technician II,David Goodman,chaim.chase@bilearner.com,SVG,Voluntarily Terminated,Full-Time,...,General - Con,27-06-1993,MA,Laborer,Female,5569,Black,Married,Fully Meets,1
Chace,3735,Gray,29-May-19,NaN,Production Technician I,Joel Nichols,chace.gray@bilearner.com,PYZ,Active,Contract,...,Wireless,11-07-1963,MA,Project Manager,Male,81455,White,Married,Fully Meets,1
Chris,3917,Vincent,19-Dec-19,31-Mar-23,Network Engineer,Ethan Allison,chris.vincent@bilearner.com,PYZ,Active,Part-Time,...,General - Con,11-04-1993,MA,Technician,Female,89635,Black,Widowed,Exceeds,3
Charlize,3962,Wagner,10-Mar-21,NaN,Sr. DBA,Joseph Patton,charlize.wagner@bilearner.com,MSC,Active,Contract,...,Aerial,18-11-1990,MA,Lineman,Female,49449,Hispanic,Divorced,Fully Meets,3
Christine,3984,Skinner,10-Feb-22,08-Jun-22,Database Administrator,Thomas Ramirez,christine.skinner@bilearner.com,EW,Active,Contract,...,Wireline Construction,23-07-1963,TX,Laborer,Female,67986,Hispanic,Single,Fully Meets,3
Chaz,1055,Webb,08-Sep-18,NaN,Software Engineer,Alec Hernandez,chaz.webb@bilearner.com,PYZ,Active,Contract,...,Field Operations,24-11-1995,MA,Laborer,Female,56708,White,Widowed,Fully Meets,3
Chaya,1158,Boyd,22-Nov-18,19-Jul-20,Production Technician I,Sean Ellis,chaya.boyd@bilearner.com,SVG,Voluntarily Terminated,Full-Time,...,Field Operations,04-07-1958,MA,Technician,Male,96001,Asian,Widowed,Fully Meets,3
Cherish,1284,Preston,08-Dec-19,NaN,Production Technician I,Chase Hardy,cherish.preston@bilearner.com,EW,Active,Contract,...,General - Eng,28-01-1985,MA,Supervisor,Female,39352,Other,Married,Fully Meets,3
Chase,1297,Lloyd,24-May-19,09-Oct-21,Production Technician II,Cindy Smith,chase.lloyd@bilearner.com,NEL,Voluntarily Terminated,Part-Time,...,Isp,08-08-1968,MA,Technician,Female,46980,Other,Married,Fully Meets,3
Christina,1354,Terry,28-Oct-20,27-Feb-22,Software Engineering Manager,Christopher Jones,christina.terry@bilearner.com,WBL,Future Start,Full-Time,...,Field Operations,07-05-1959,MA,Top Hand,Female,79778,Black,Widowed,Fully Meets,3
Chanel,1466,Dougherty,04-Mar-21,NaN,Production Technician I,Jennifer Dillon,chanel.dougherty@bilearner.com,PYZ,Active,Full-Time,...,Billable Consultants,08-03-1989,MA,Engineer,Female,50559,White,Widowed,Exceeds,3
Chaim,1521,Patrick,08-Dec-20,07-Sep-21,Production Technician I,Jackie Poole,chaim.patrick@bilearner.com,SVG,Active,Contract,...,Wireline Construction,15-04-1990,MA,Groundman,Male,16162,Black,Single,Needs Improvement,3
Chance,1572,Warner,28-Sep-21,09-Oct-22,Production Technician I,Julie Porter,chance.warner@bilearner.com,BPC,Active,Part-Time,...,Fielders,08-04-1951,MA,Engineer,Female,18550,Black,Married,Fully Meets,3
Charlee,1592,Wiggins,14-Jun-20,18-Jul-23,Production Technician I,Elizabeth Allen,charlee.wiggins@bilearner.com,WBL,Active,Full-Time,...,Engineers,15-08-1981,MA,Engineer,Male,20973,Other,Single,Exceeds,3
Charlie,1595,Ramirez,09-Jun-23,NaN,Production Technician I,Laura Meadows,charlie.ramirez@bilearner.com,BPC,Active,Part-Time,...,General - Eng,11-09-1969,MA,Administrative,Female,75995,Black,Married,Exceeds,3
Chris,1596,Johnson,02-Mar-20,25-May-20,Production Technician I,Jennifer Mendez,chris.johnson@bilearner.com,CCDR,Future Start,Contract,...,General - Sga,15-08-1958,MA,Administrator,Female,2999,Other,Married,Exceeds,3
Charlie,1624,Wang,12-May-23,16-May-23,Senior BI Developer,Maria Rivera,charlie.wang@bilearner.com,WBL,Active,Full-Time,...,Field Operations,22-10-1996,MA,Top Hand,Male,1887,White,Widowed,Needs Improvement,3
Chance,1631,Braun,17-Jun-23,19-Jul-23,BI Developer,Jessica Peters,chance.braun@bilearner.com,CCDR,Terminated for Cause,Full-Time,...,Executive,24-10-1986,MA,Executive Assistant,Female,20602,White,Widowed,Fully Meets,3
Charlee,1648,Calhoun,14-May-21,NaN,Sales Manager,Karen Cordova,charlee.calhoun@bilearner.com,MSC,Active,Part-Time,...,Aerial,19-08-1977,MA,Driver,Male,96848,White,Single,Fully Meets,3
Chloe,1655,Gould,18-Jul-23,NaN,Area Sales Manager,Lisa Thompson,chloe.gould@bilearner.com,TNS,Active,Part-Time,...,Wireline Construction,01-09-1942,MA,Project Manager,Male,3563,Black,Married,Fully Meets,3
Chance,1794,Blackwell,26-May-21,NaN,Production Technician I,James Ashley,chance.blackwell@bilearner.com,CCDR,Active,Contract,...,General - Sga,13-08-1963,MA,Administrator,Female,95802,White,Widowed,Fully Meets,3
Chase,1987,Horn,09-Nov-18,NaN,Production Technician I,Richard Davis II,chase.horn@bilearner.com,MSC,Active,Full-Time,...,General - Sga,27-05-1967,MA,Administrator,Female,75570,White,Single,Fully Meets,3
Chace,2123,Farley,10-Sep-21,NaN,Production Technician I,Jackie Tran,chace.farley@bilearner.com,CCDR,Active,Contract,...,Catv,12-02-1979,MA,Project Manager,Female,96364,White,Widowed,Exceeds,2
Chasity,2126,Kennedy,08-Mar-21,07-Oct-22,Production Technician I,Steven Logan,chasity.kennedy@bilearner.com,MSC,Active,Part-Time,...,Technology / It,20-06-1969,MA,Helpdesk,Female,35121,Black,Married,PIP,1
Cheyanne,2149,Hess,02-May-21,27-Jun-23,Production Technician I,Charles Williams,cheyanne.hess@bilearner.com,PYZ,Voluntarily Terminated,Full-Time,...,Project Management - Con,26-03-1997,MA,Coordinator,Female,90636,White,Single,Exceeds,5
Charlize,2173,Wong,14-Aug-21,08-Oct-21,Production Technician I,Ryan Armstrong,charlize.wong@bilearner.com,SVG,Voluntarily Terminated,Contract,...,Engineers,04-10-1987,MA,Engineer,Female,6115,Asian,Divorced,Exceeds,3
Charles,2282,Bozzi,25-Apr-19,NaN,Production Manager,Richard Jackson,charles.bozzi@bilearner.com,PL,Active,Part-Time,...,Fielders,28-07-1967,MA,Engineer,Male,1901,Asian,Single,Fully Meets,4
Charlee,2354,Navarro,07-Jan-22,29-Jun-22,Data Analyst,Elizabeth Houston,charlee.navarro@bilearner.com,PYZ,Active,Part-Time,...,Wireline Construction,02-09-1971,MA,Clerk,Female,61793,White,Divorced,Fully Meets,2
Chana,2449,Fox,29-Apr-20,10-Jul-21,Production Manager,Desiree Blair,chana.fox@bilearner.com,SVG,Voluntarily Terminated,Part-Time,...,Aerial,10-02-1986,MA,Lineman,Female,63427,Hispanic,Single,Fully Meets,4
Charlie,2502,Brady,27-Jan-19,NaN,Software Engineer,Sandra Rodriguez,charlie.brady@bilearner.com,SVG,Active,Part-Time,...,Wireline Construction,06-06-1999,MA,Supervisor,Male,25819,White,Divorced,Fully Meets,2
Chandler,2533,Reynolds,05-May-21,NaN,IT Manager - DB,Lauren Baker,chandler.reynolds@bilearner.com,PL,Active,Full-Time,...,Field Operations,13-06-1966,MA,Technician,Male,53235,White,Divorced,Fully Meets,1
Charles,2624,Howard,11-Jun-23,28-Jul-23,Area Sales Manager,Janet Andrews,charles.howard@bilearner.com,SVG,Active,Part-Time,...,Wireline Construction,22-07-1984,AL,Supervisor,Male,12964,Other,Single,Fully Meets,2
Charles,2628,Coleman,07-Dec-21,NaN,Area Sales Manager,Thomas Roberts,charles.coleman@bilearner.com,BPC,Active,Part-Time,...,Sales & Marketing,19-11-1991,TN,Vp,Male,33113,Hispanic,Divorced,Fully Meets,2
Christine,2679,Giles,17-Nov-22,NaN,Area Sales Manager,Heather Wright,christine.giles@bilearner.com,TNS,Active,Contract,...,General - Con,20-10-1951,ID,Foreman,Male,80607,Hispanic,Divorced,Fully Meets,5
Charlize,2683,Ballard,31-Dec-21,NaN,Area Sales Manager,Kimberly Soto,charlize.ballard@bilearner.com,PL,Active,Contract,...,General - Con,14-10-1952,WA,Laborer,Female,86439,Other,Divorced,Fully Meets,4
Cheyenne,2720,Herman,08-Jan-22,03-Sep-22,Area Sales Manager,Kathleen Hickman,cheyenne.herman@bilearner.com,PL,Active,Contract,...,Field Operations,13-08-1994,NC,Top Hand,Female,26500,Asian,Widowed,Fully Meets,4
Cheyanne,2913,Munoz,03-Dec-19,NaN,Production Technician I,Jessica Brown,cheyanne.munoz@bilearner.com,WBL,Active,Full-Time,...,Splicing,15-10-1950,MA,Splicer,Male,70198,Hispanic,Divorced,Needs Improvement,2
Charlize,2950,Rocha,14-Sep-18,04-Jan-19,Production Technician II,James Chapman,charlize.rocha@bilearner.com,MSC,Voluntarily Terminated,Part-Time,...,People Services,04-01-1943,MA,Manager,Female,75308,White,Married,Needs Improvement,4
Cherly,2972,Robinson,13-Feb-23,NaN,Production Technician I,Summer Figueroa,cherly.robinson@bilearner.com,TNS,Active,Full-Time,...,General - Con,03-04-1948,MA,Laborer,Female,1460,Other,Widowed,Fully Meets,1
Charlie,3254,Carson,23-Feb-21,13-Jul-22,Production Technician I,Samantha Gilbert,charlie.carson@bilearner.com,BPC,Leave of Absence,Full-Time,...,General - Sga,20-08-1989,MA,Administration,Male,25093,Other,Widowed,Fully Meets,3
Chace,3426,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,Full-Time,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [40]:
employees.filter(regex='^L.*' , axis=1)

             LastName  LocationCode
FirstName
Uriah         Bridges         34904
Paula           Small          6593
Edward           Buck          2330
Michael       Riordan         58782
Jasmine         Onque         33174
...               ...           ...
Jakobe       Erickson         44500
Adyson     Strickland         35444
Annabel       Wilkins          6608
Kendra          Braun          3807
Chace            Kerr         57487

[3000 rows x 2 columns]