In [7]:
import pandas as pd
from sqlalchemy import create_engine
# connection string
engine = create_engine(
    "postgresql+psycopg2://udemy:udemy123@localhost:5434/udemy_master_of_pandas"
)

# read table
employees = pd.read_sql("SELECT * FROM archive.employee_data;", engine)

In [8]:
employees

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
3,3430,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,...,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [10]:
 employees.columns

Index(['EmpID', 'FirstName', 'LastName', 'StartDate', 'ExitDate', 'Title',
       'Supervisor', 'ADEmail', 'BusinessUnit', 'EmployeeStatus',
       'EmployeeType', 'PayZone', 'EmployeeClassificationType',
       'TerminationType', 'TerminationDescription', 'DepartmentType',
       'Division', 'DOB', 'State', 'JobFunctionDescription', 'GenderCode',
       'LocationCode', 'RaceDesc', 'MaritalDesc', 'Performance Score',
       'Current Employee Rating'],
      dtype='str')

In [14]:
 employees['Title']

0       Production Technician I
1       Production Technician I
2            Area Sales Manager
3            Area Sales Manager
4            Area Sales Manager
                 ...
2995    Production Technician I
2996    Production Technician I
2997    Production Technician I
2998    Production Technician I
2999    Production Technician I
Name: Title, Length: 3000, dtype: str

In [15]:
employees['Title'].unique()

<StringArray>
[     'Production Technician I',           'Area Sales Manager',
     'Production Technician II',                   'IT Support',
             'Network Engineer',         'Sr. Network Engineer',
     'Principal Data Architect',         'Enterprise Architect',
                      'Sr. DBA',       'Database Administrator',
                 'Data Analyst',                'Data Analyst ',
               'Data Architect',                          'CIO',
                  'BI Director',               'Sr. Accountant',
 'Software Engineering Manager',            'Software Engineer',
      'Shared Services Manager',          'Senior BI Developer',
           'Production Manager',              'President & CEO',
     'Administrative Assistant',                 'Accountant I',
                'Sales Manager',                 'BI Developer',
         'IT Manager - Support',           'IT Manager - Infra',
              'IT Manager - DB',            'Director of Sales',
       'Director of Operations',                  'IT Director']
Length: 32, dtype: str

In [16]:
employees['Title'].unique()=='Production Technician I'

array([ True, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False, False, False, False, False,
       False, False, False, False, False])

In [17]:
 employees['Title']=='Production Technician I'

0        True
1        True
2       False
3       False
4       False
        ...
2995     True
2996     True
2997     True
2998     True
2999     True
Name: Title, Length: 3000, dtype: bool

In [21]:
employees[employees['Title']=='Production Technician I']

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
131,3558,Mildred,Gentry,30-Dec-18,NaN,Production Technician I,Erin Moore,mildred.gentry@bilearner.com,MSC,Active,...,Yard (Material Handling),04-06-1959,MA,Manager,Female,2145,Black,Single,Fully Meets,1
132,3559,Wilson K,Adinolfi,06-Nov-19,06-Sep-20,Production Technician I,Andrea Gutierrez,wilson k.adinolfi@bilearner.com,NEL,Active,...,Field Operations,18-11-1991,MA,Assistant,Male,1960,White,Single,Fully Meets,2
133,3560,Joanne,Handschiegl,01-Jun-22,NaN,Production Technician I,Wanda Ross DDS,joanne.handschiegl@bilearner.com,MSC,Active,...,Field Operations,18-02-1954,MA,Technician,Female,2127,Asian,Divorced,Exceeds,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,...,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2
2999,3426,Chace,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [22]:
employees[employees['Title']=='Data Architect']

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
532,3959,Braylen,Mendoza,11-Nov-22,14-Jul-23,Data Architect,Douglas Chapman,braylen.mendoza@bilearner.com,PYZ,Terminated for Cause,...,General - Con,20-08-1988,TX,Foreman,Male,42665,Hispanic,Single,Fully Meets,3
547,3974,Zander,Franco,25-Dec-18,10-Jul-19,Data Architect,Ronnie Garcia,zander.franco@bilearner.com,BPC,Terminated for Cause,...,General - Eng,07-01-1986,TX,Engineer,Male,97255,Other,Married,Exceeds,3
560,3987,Aydan,Benjamin,25-Feb-22,19-Jul-22,Data Architect,Lindsay Nelson,aydan.benjamin@bilearner.com,PYZ,Terminated for Cause,...,Catv,03-05-1982,TX,Supervisor,Male,81376,Other,Widowed,Exceeds,3
573,4000,Angelique,Mann,26-Oct-19,08-Jun-21,Data Architect,Eugene Morgan,angelique.mann@bilearner.com,PYZ,Terminated for Cause,...,Field Operations,31-03-1960,TX,Technician,Male,18464,Black,Divorced,Fully Meets,3
1200,1626,Katie,Roper,17-Sep-20,08-Jun-21,Data Architect,William Green,katie.roper@bilearner.com,PL,Active,...,General - Con,12-05-1947,MA,Technician,Female,2056,Other,Married,Needs Improvement,3

In [24]:
employees['EmployeeStatus'].unique()

<StringArray>
[                'Active',           'Future Start', 'Voluntarily Terminated',
       'Leave of Absence',   'Terminated for Cause']
Length: 5, dtype: str

In [25]:
employees['EmployeeStatus']=='Leave of Absence'

0       False
1       False
2       False
3       False
4       False
        ...
2995     True
2996    False
2997    False
2998    False
2999    False
Name: EmployeeStatus, Length: 3000, dtype: bool

In [26]:
employees[employees['EmployeeStatus']=='Leave of Absence']

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
389,3814,Jyoti,Lajiri,07-Jan-19,05-Sep-20,Sr. Network Engineer,Karen Crawford,jyoti.lajiri@bilearner.com,EW,Leave of Absence,...,Engineers,17-04-1955,MA,Coordinator,Male,2169,Black,Widowed,Fully Meets,3
407,3832,Sloane,Rasmussen,02-Aug-21,29-Sep-22,Sr. DBA,Melinda Mcintyre,sloane.rasmussen@bilearner.com,EW,Leave of Absence,...,Project Management - Eng,07-09-1964,MA,Planner,Female,96097,Hispanic,Widowed,PIP,3
415,3842,Kyla,Durham,20-Aug-20,11-Aug-21,Enterprise Architect,Clayton Robertson,kyla.durham@bilearner.com,SVG,Leave of Absence,...,Aerial,19-07-1951,MA,Lineman,Female,40402,White,Divorced,Fully Meets,3
416,3843,Cassidy,Maddox,16-Jul-23,30-Jul-23,Sr. DBA,Melissa Pineda,cassidy.maddox@bilearner.com,EW,Leave of Absence,...,Engineers,07-02-1977,MA,Engineer,Female,21480,Asian,Single,Fully Meets,3
424,3851,Vance,Marquez,18-Jan-19,30-Mar-20,Sr. Network Engineer,Thomas Hanson,vance.marquez@bilearner.com,NEL,Leave of Absence,...,Executive,07-07-1994,CT,Manager,Male,38058,Black,Married,PIP,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2963,3390,Lizeth,Middleton,21-Oct-22,05-Jan-23,Production Technician II,Joanna Nguyen,lizeth.middleton@bilearner.com,CCDR,Leave of Absence,...,Billable Consultants,10-01-1969,MA,Engineer,Female,90024,Hispanic,Married,Fully Meets,1
2974,3401,Taniya,Kane,10-Nov-21,04-Jun-23,Production Technician I,Scott Powell,taniya.kane@bilearner.com,EW,Leave of Absence,...,Field Operations,11-04-1973,MA,Laborer,Male,3403,Hispanic,Married,Fully Meets,1
2977,3404,Willie,Howe,25-Apr-19,11-Nov-22,Production Technician I,Ivan Bryant,willie.howe@bilearner.com,PYZ,Leave of Absence,...,Field Operations,20-01-1985,MA,Driller,Female,58775,Other,Divorced,Fully Meets,2
2978,3405,Selina,Jefferson,13-Jan-20,21-Oct-22,Production Technician I,Karen Lin,selina.jefferson@bilearner.com,WBL,Leave of Absence,...,Field Operations,02-03-1979,MA,Engineer,Female,12351,White,Single,Fully Meets,1
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3

In [29]:
 employees['EmployeeType'].unique()

<StringArray>
['Contract', 'Full-Time', 'Part-Time']
Length: 3, dtype: str

In [30]:
employees['EmployeeType']=='Full-Time'

0       False
1       False
2        True
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999     True
Name: EmployeeType, Length: 3000, dtype: bool

In [31]:
employees[employees['EmployeeType']=='Full-Time']

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
6,3433,Latia,Costa,06-Apr-22,03-Jul-23,Area Sales Manager,Jacob Braun,latia.costa@bilearner.com,WBL,Active,...,General - Eng,01-07-1942,CA,Technician,Female,90007,Hispanic,Divorced,Exceeds,4
11,3438,Dheepa,Nguyen,10-Aug-18,04-Nov-19,Area Sales Manager,Brian Miller,dheepa.nguyen@bilearner.com,MSC,Active,...,General - Con,06-04-1948,GA,Technician,Female,30428,Asian,Married,Fully Meets,3
12,3439,Bartholemew,Khemmich,25-May-22,27-Nov-22,Area Sales Manager,Charles Parks,bartholemew.khemmich@bilearner.com,EW,Active,...,Splicing,24-11-1981,CO,Splicer,Male,80820,Other,Single,Fully Meets,3
15,3442,Kaylah,Moon,09-Jul-19,16-Jun-22,Area Sales Manager,Ashley Scott,kaylah.moon@bilearner.com,PYZ,Active,...,Field Operations,24-11-1952,MA,Laborer,Male,2810,Black,Single,Exceeds,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2973,3400,Lorenzo,Short,21-Sep-21,NaN,Production Technician I,Samantha Thomas,lorenzo.short@bilearner.com,MSC,Active,...,Shop (Fleet),04-06-1970,MA,Mechanic,Female,90974,Black,Divorced,Fully Meets,1
2984,3411,Brenda,Boone,06-Oct-22,NaN,Production Technician II,Howard Ryan,brenda.boone@bilearner.com,CCDR,Active,...,General - Eng,20-03-1949,MA,Administrative,Female,24028,Asian,Single,Fully Meets,2
2988,3415,Julien,Cisneros,09-Sep-22,16-Mar-23,Production Technician I,Jerry Johnson,julien.cisneros@bilearner.com,TNS,Voluntarily Terminated,...,Splicing,14-10-1974,MA,Driver,Male,23971,Hispanic,Widowed,Fully Meets,3
2989,3416,Aron,Waters,02-Oct-20,NaN,Production Technician I,Amanda Fisher,aron.waters@bilearner.com,BPC,Active,...,Finance & Accounting,18-12-1992,MA,Director,Male,46381,Asian,Married,Fully Meets,2
2999,3426,Chace,Kerr,27-Apr-22,NaN,Production Technician I,Javier Mccall,chace.kerr@bilearner.com,BPC,Active,...,Field Operations,11-09-1990,MA,Warehouse Technician,Female,57487,White,Married,Fully Meets,2

In [32]:
employees[employees['EmployeeType']=='Contract']

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
3,3430,Michael,Riordan,21-Jun-21,NaN,Area Sales Manager,Rebekah Wright,michael.riordan@bilearner.com,CCDR,Active,...,Finance & Accounting,04-04-1998,ND,Clerk,Male,58782,Other,Single,Fully Meets,2
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
5,3432,Maruk,Fraval,17-Jan-20,NaN,Area Sales Manager,Sheri Campos,maruk.fraval@bilearner.com,BPC,Active,...,Field Operations,03-04-1949,CT,Driver,Male,6050,Black,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2987,3414,Hunter,Silva,03-Jun-22,NaN,Production Technician I,Brandi Clark,hunter.silva@bilearner.com,MSC,Active,...,General - Con,04-05-1998,MA,Foreman,Female,44418,Hispanic,Married,Exceeds,3
2992,3419,Stanley,Reyes,14-Oct-19,NaN,Production Technician I,Miss Sandra Mckinney,stanley.reyes@bilearner.com,MSC,Active,...,General - Con,05-12-1952,MA,Foreman,Female,39578,Black,Divorced,Fully Meets,2
2993,3420,Levi,Hayden,10-Oct-20,05-Aug-22,Production Technician I,Lynn Smith,levi.hayden@bilearner.com,NEL,Active,...,Field Operations,10-08-1944,MA,Laborer,Female,18079,Other,Married,Fully Meets,2
2997,3424,Annabel,Wilkins,09-Dec-20,04-Aug-22,Production Technician I,Mr. James Castillo,annabel.wilkins@bilearner.com,TNS,Voluntarily Terminated,...,Wireline Construction,27-01-1997,MA,Laborer,Male,6608,White,Single,Fully Meets,2
2998,3425,Kendra,Braun,28-May-19,23-Oct-21,Production Technician I,Michael Woods,kendra.braun@bilearner.com,WBL,Voluntarily Terminated,...,Aerial,28-05-1954,MA,Foreman,Female,3807,Hispanic,Divorced,Fully Meets,2

In [33]:
employees[employees['EmployeeType']=='Part-Time']

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
9,3436,Joseph,Martins,21-Jan-22,29-Jun-23,Area Sales Manager,George Jenkins,joseph.martins@bilearner.com,BPC,Active,...,Engineers,11-11-1949,TX,Engineer,Male,78207,Asian,Widowed,Fully Meets,5
14,3441,Prater,Jeremy,28-Apr-19,NaN,Area Sales Manager,Tyler Lewis,prater.jeremy@bilearner.com,BPC,Active,...,General - Con,21-11-1989,NV,Lineman,Male,89139,Asian,Widowed,Exceeds,4
19,3446,Hector,Dalton,24-Aug-21,NaN,Area Sales Manager,Sydney French,hector.dalton@bilearner.com,BPC,Active,...,Field Operations,01-05-1996,TX,Driller,Female,16325,White,Divorced,Exceeds,2
20,3447,Mariela,Schultz,26-May-20,18-Jun-23,Area Sales Manager,Michelle Evans MD,mariela.schultz@bilearner.com,CCDR,Future Start,...,General - Con,17-02-1964,TX,Technician,Female,43481,Asian,Widowed,Fully Meets,3
25,3452,Jaydon,Blackburn,08-Nov-22,NaN,Area Sales Manager,Debbie Crosby,jaydon.blackburn@bilearner.com,PYZ,Active,...,General - Con,07-01-1947,IN,Foreman,Male,12122,Black,Divorced,Fully Meets,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2990,3417,Brayden,Singh,07-Feb-22,NaN,Production Technician I,Clayton Davis,brayden.singh@bilearner.com,CCDR,Active,...,Splicing,26-09-2000,MA,Splicer,Female,71282,Other,Widowed,Fully Meets,1
2991,3418,Karma,Palmer,14-Oct-22,NaN,Production Technician I,Nicholas Price,karma.palmer@bilearner.com,EW,Active,...,General - Con,12-08-1996,MA,Coordinator,Female,40277,Asian,Widowed,Fully Meets,4
2994,3421,Brenden,Leach,09-May-22,08-Sep-22,Production Technician I,Donna Lawson,brenden.leach@bilearner.com,PL,Active,...,Wireless,11-06-1959,MA,Foreman,Female,57340,Other,Divorced,Fully Meets,1
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3

In [34]:
 employees['PayZone'].unique()

<StringArray>
['Zone C', 'Zone A', 'Zone B']
Length: 3, dtype: str

In [35]:
 employees['PayZone'] == 'Zone C'

0        True
1       False
2       False
3       False
4       False
        ...
2995     True
2996    False
2997    False
2998    False
2999    False
Name: PayZone, Length: 3000, dtype: bool

In [36]:
employees[ employees['PayZone'] == 'Zone C']

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
7,3434,Sharlene,Terry,06-Nov-20,29-Jan-23,Area Sales Manager,Tracy Marquez,sharlene.terry@bilearner.com,CCDR,Active,...,Engineers,07-03-1957,OR,Engineer,Female,97756,White,Divorced,Fully Meets,2
11,3438,Dheepa,Nguyen,10-Aug-18,04-Nov-19,Area Sales Manager,Brian Miller,dheepa.nguyen@bilearner.com,MSC,Active,...,General - Con,06-04-1948,GA,Technician,Female,30428,Asian,Married,Fully Meets,3
16,3443,Kristen,Tate,05-Apr-21,12-May-23,Area Sales Manager,Lauren Jones,kristen.tate@bilearner.com,WBL,Active,...,Project Management - Con,08-04-1994,KY,Coordinator,Male,2621,Asian,Widowed,Fully Meets,3
18,3445,Reid,Park,16-Jan-21,NaN,Area Sales Manager,Michelle Mitchell,reid.park@bilearner.com,PL,Active,...,Project Management - Con,07-12-1985,KY,Supervisor,Female,5360,Other,Married,Exceeds,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2980,3407,Kamila,Sanders,15-Apr-21,11-May-23,Production Technician II,Aaron Stewart,kamila.sanders@bilearner.com,WBL,Active,...,Field Operations,26-02-1953,MA,Construction Manager,Female,18000,Asian,Single,Fully Meets,5
2983,3410,Laci,Klein,18-Dec-18,NaN,Production Technician II,Kyle Hicks,laci.klein@bilearner.com,BPC,Active,...,People Services,07-07-1980,MA,Manager,Male,41572,Hispanic,Widowed,Fully Meets,3
2987,3414,Hunter,Silva,03-Jun-22,NaN,Production Technician I,Brandi Clark,hunter.silva@bilearner.com,MSC,Active,...,General - Con,04-05-1998,MA,Foreman,Female,44418,Hispanic,Married,Exceeds,3
2992,3419,Stanley,Reyes,14-Oct-19,NaN,Production Technician I,Miss Sandra Mckinney,stanley.reyes@bilearner.com,MSC,Active,...,General - Con,05-12-1952,MA,Foreman,Female,39578,Black,Divorced,Fully Meets,2
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3

In [37]:
employees['Current Employee Rating'].unique()

array([4, 3, 2, 5, 1])

In [38]:
employees['Current Employee Rating'] == 4

0        True
1       False
2        True
3       False
4       False
        ...
2995    False
2996    False
2997    False
2998    False
2999    False
Name: Current Employee Rating, Length: 3000, dtype: bool

In [39]:
employees[employees['Current Employee Rating'] == 4]

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
6,3433,Latia,Costa,06-Apr-22,03-Jul-23,Area Sales Manager,Jacob Braun,latia.costa@bilearner.com,WBL,Active,...,General - Eng,01-07-1942,CA,Technician,Female,90007,Hispanic,Divorced,Exceeds,4
14,3441,Prater,Jeremy,28-Apr-19,NaN,Area Sales Manager,Tyler Lewis,prater.jeremy@bilearner.com,BPC,Active,...,General - Con,21-11-1989,NV,Lineman,Male,89139,Asian,Widowed,Exceeds,4
18,3445,Reid,Park,16-Jan-21,NaN,Area Sales Manager,Michelle Mitchell,reid.park@bilearner.com,PL,Active,...,Project Management - Con,07-12-1985,KY,Supervisor,Female,5360,Other,Married,Exceeds,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2950,3377,Cruz,Ashley,24-Feb-20,13-May-23,Production Technician I,Evan Schultz,cruz.ashley@bilearner.com,BPC,Active,...,Splicing,06-09-1989,MA,Foreman,Female,52336,Asian,Widowed,Exceeds,4
2952,3379,Marquis,Joseph,09-Apr-23,14-Jun-23,Production Technician I,Walter Henry,marquis.joseph@bilearner.com,SVG,Leave of Absence,...,Technology / It,23-06-1973,MA,Helpdesk,Female,48347,Hispanic,Married,Exceeds,4
2969,3396,Stephen,Mcmillan,05-Apr-21,29-Nov-21,Production Technician I,Stephanie Petty,stephen.mcmillan@bilearner.com,SVG,Voluntarily Terminated,...,General - Con,30-11-1949,MA,Foreman,Female,49024,Asian,Married,Fully Meets,4
2982,3409,Brenton,Zavala,08-Oct-22,04-Feb-23,Production Technician II,Jonathan Brown,brenton.zavala@bilearner.com,PL,Active,...,Yard (Material Handling),15-03-1943,MA,Laborer,Male,82704,Asian,Divorced,Fully Meets,4
2991,3418,Karma,Palmer,14-Oct-22,NaN,Production Technician I,Nicholas Price,karma.palmer@bilearner.com,EW,Active,...,General - Con,12-08-1996,MA,Coordinator,Female,40277,Asian,Widowed,Fully Meets,4

In [40]:
employees[employees['Current Employee Rating'] > 3]

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
6,3433,Latia,Costa,06-Apr-22,03-Jul-23,Area Sales Manager,Jacob Braun,latia.costa@bilearner.com,WBL,Active,...,General - Eng,01-07-1942,CA,Technician,Female,90007,Hispanic,Divorced,Exceeds,4
9,3436,Joseph,Martins,21-Jan-22,29-Jun-23,Area Sales Manager,George Jenkins,joseph.martins@bilearner.com,BPC,Active,...,Engineers,11-11-1949,TX,Engineer,Male,78207,Asian,Widowed,Fully Meets,5
10,3437,Myriam,Givens,04-Aug-23,NaN,Area Sales Manager,Troy White,myriam.givens@bilearner.com,SVG,Active,...,Field Operations,26-01-1964,IN,Technician,Female,46204,Other,Single,Fully Meets,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2979,3406,Serenity,Montgomery,25-Mar-20,26-Apr-23,Production Technician I,Tina Munoz,serenity.montgomery@bilearner.com,NEL,Voluntarily Terminated,...,Finance & Accounting,17-05-1955,MA,Administration,Female,24805,Other,Single,Fully Meets,5
2980,3407,Kamila,Sanders,15-Apr-21,11-May-23,Production Technician II,Aaron Stewart,kamila.sanders@bilearner.com,WBL,Active,...,Field Operations,26-02-1953,MA,Construction Manager,Female,18000,Asian,Single,Fully Meets,5
2982,3409,Brenton,Zavala,08-Oct-22,04-Feb-23,Production Technician II,Jonathan Brown,brenton.zavala@bilearner.com,PL,Active,...,Yard (Material Handling),15-03-1943,MA,Laborer,Male,82704,Asian,Divorced,Fully Meets,4
2986,3413,Jovanny,Matthews,25-Nov-19,NaN,Production Technician II,Jackson Ward,jovanny.matthews@bilearner.com,EW,Active,...,Field Operations,15-12-1962,MA,Laborer,Female,74549,White,Single,Fully Meets,5
2991,3418,Karma,Palmer,14-Oct-22,NaN,Production Technician I,Nicholas Price,karma.palmer@bilearner.com,EW,Active,...,General - Con,12-08-1996,MA,Coordinator,Female,40277,Asian,Widowed,Fully Meets,4

In [41]:
employees[employees['Current Employee Rating'] >= 3]

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
1,3428,Paula,Small,11-Feb-23,NaN,Production Technician I,Renee Mccormick,paula.small@bilearner.com,EW,Active,...,Aerial,30-08-1965,MA,Labor,Male,6593,Hispanic,Widowed,Fully Meets,3
2,3429,Edward,Buck,10-Dec-18,NaN,Area Sales Manager,Crystal Walker,edward.buck@bilearner.com,PL,Active,...,General - Sga,06-10-1991,MA,Assistant,Male,2330,Hispanic,Widowed,Fully Meets,4
4,3431,Jasmine,Onque,29-Jun-19,NaN,Area Sales Manager,Jason Kim,jasmine.onque@bilearner.com,TNS,Active,...,General - Con,29-08-1969,FL,Laborer,Female,33174,Other,Married,Fully Meets,3
5,3432,Maruk,Fraval,17-Jan-20,NaN,Area Sales Manager,Sheri Campos,maruk.fraval@bilearner.com,BPC,Active,...,Field Operations,03-04-1949,CT,Driver,Male,6050,Black,Married,Fully Meets,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2987,3414,Hunter,Silva,03-Jun-22,NaN,Production Technician I,Brandi Clark,hunter.silva@bilearner.com,MSC,Active,...,General - Con,04-05-1998,MA,Foreman,Female,44418,Hispanic,Married,Exceeds,3
2988,3415,Julien,Cisneros,09-Sep-22,16-Mar-23,Production Technician I,Jerry Johnson,julien.cisneros@bilearner.com,TNS,Voluntarily Terminated,...,Splicing,14-10-1974,MA,Driver,Male,23971,Hispanic,Widowed,Fully Meets,3
2991,3418,Karma,Palmer,14-Oct-22,NaN,Production Technician I,Nicholas Price,karma.palmer@bilearner.com,EW,Active,...,General - Con,12-08-1996,MA,Coordinator,Female,40277,Asian,Widowed,Fully Meets,4
2995,3422,Jakobe,Erickson,22-Jun-22,07-Aug-22,Production Technician I,Bethany Carter,jakobe.erickson@bilearner.com,PYZ,Leave of Absence,...,Engineers,23-06-1998,MA,Model Assistant,Female,44500,Other,Widowed,Fully Meets,3
2996,3423,Adyson,Strickland,28-Dec-20,NaN,Production Technician I,Caroline Harris,adyson.strickland@bilearner.com,SVG,Active,...,Engineers,10-06-2001,MA,Engineer,Male,35444,Black,Widowed,Fully Meets,3

In [44]:
employees[(employees['Current Employee Rating'] > 3) & (employees['PayZone'] == 'Zone C')]

,EmpID,FirstName,LastName,StartDate,ExitDate,Title,Supervisor,ADEmail,BusinessUnit,EmployeeStatus,...,Division,DOB,State,JobFunctionDescription,GenderCode,LocationCode,RaceDesc,MaritalDesc,Performance Score,Current Employee Rating
0,3427,Uriah,Bridges,20-Sep-19,NaN,Production Technician I,Peter Oneill,uriah.bridges@bilearner.com,CCDR,Active,...,Finance & Accounting,07-10-1969,MA,Accounting,Female,34904,White,Widowed,Fully Meets,4
18,3445,Reid,Park,16-Jan-21,NaN,Area Sales Manager,Michelle Mitchell,reid.park@bilearner.com,PL,Active,...,Project Management - Con,07-12-1985,KY,Supervisor,Female,5360,Other,Married,Exceeds,4
26,3453,Bridger,Carter,13-Oct-22,NaN,Area Sales Manager,Elizabeth Taylor,bridger.carter@bilearner.com,WBL,Active,...,Fielders,07-04-1982,MA,Engineer,Male,87065,White,Widowed,Fully Meets,4
27,3454,Leon,Beard,11-Sep-22,NaN,Area Sales Manager,Brian Dunlap,leon.beard@bilearner.com,PYZ,Active,...,General - Con,29-01-1970,KY,Foreman,Male,10415,Hispanic,Married,Needs Improvement,4
28,3455,Charity,Miranda,29-Jun-21,05-Jul-22,Area Sales Manager,Daniel Rodriguez,charity.miranda@bilearner.com,WBL,Active,...,Project Management - Eng,18-01-1999,KY,Manager,Male,3763,Other,Widowed,Exceeds,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2945,3372,Kylie,Roman,14-Jan-23,14-Mar-23,Production Technician I,Tammy Small,kylie.roman@bilearner.com,TNS,Voluntarily Terminated,...,Project Management - Con,27-05-1992,MA,Manager,Female,94040,Asian,Divorced,Fully Meets,4
2952,3379,Marquis,Joseph,09-Apr-23,14-Jun-23,Production Technician I,Walter Henry,marquis.joseph@bilearner.com,SVG,Leave of Absence,...,Technology / It,23-06-1973,MA,Helpdesk,Female,48347,Hispanic,Married,Exceeds,4
2955,3382,Romeo,Gordon,10-Nov-18,NaN,Production Technician I,Thomas Elliott,romeo.gordon@bilearner.com,TNS,Active,...,Field Operations,20-05-1970,MA,Administrator,Male,59153,Other,Divorced,Exceeds,5
2979,3406,Serenity,Montgomery,25-Mar-20,26-Apr-23,Production Technician I,Tina Munoz,serenity.montgomery@bilearner.com,NEL,Voluntarily Terminated,...,Finance & Accounting,17-05-1955,MA,Administration,Female,24805,Other,Single,Fully Meets,5
2980,3407,Kamila,Sanders,15-Apr-21,11-May-23,Production Technician II,Aaron Stewart,kamila.sanders@bilearner.com,WBL,Active,...,Field Operations,26-02-1953,MA,Construction Manager,Female,18000,Asian,Single,Fully Meets,5