In [2]:
import pandas as pd
from sqlalchemy import create_engine
# connection string
engine = create_engine(
    "postgresql+psycopg2://udemy:udemy123@localhost:5434/udemy_master_of_pandas"
)

# read table
employees = pd.read_sql("SELECT * FROM master.employees;", engine)

In [3]:
employees

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,None
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,None,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [4]:
employees.sort_index()

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,None
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
...,...,...,...,...,...,...,...,...
995,Henry,None,11/23/2014,6:09 AM,132483,16.655,False,Distribution
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales

In [7]:
employees.sort_index(ascending=False)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales
998,Larry,Male,4/20/2013,4:45 PM,60500,11.985,False,Business Development
997,Russell,Male,5/20/2013,12:39 PM,96914,1.421,False,Product
996,Phillip,Male,1/31/1984,6:30 AM,42392,19.675,False,Finance
995,Henry,None,11/23/2014,6:09 AM,132483,16.655,False,Distribution
...,...,...,...,...,...,...,...,...
4,Larry,Male,1/24/1998,4:47 PM,101004,1.389,True,Client Services
3,Jerry,Male,3/4/2005,1:00 PM,138705,9.340,True,Finance
2,Maria,Female,4/23/1993,11:17 AM,130590,11.858,False,Finance
1,Thomas,Male,3/31/1996,6:53 AM,61933,4.170,True,None
0,Douglas,Male,8/6/1993,12:42 PM,97308,6.945,True,Marketing

In [8]:
employees.axes

[RangeIndex(start=0, stop=1000, step=1),
 Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
        'Bonus %', 'Senior Management', 'Team'],
       dtype='object')]

empolyees.axes[0]

In [10]:
employees.axes[0]

RangeIndex(start=0, stop=1000, step=1)

In [11]:
employees.axes[1]

Index(['First Name', 'Gender', 'Start Date', 'Last Login Time', 'Salary',
       'Bonus %', 'Senior Management', 'Team'],
      dtype='object')

In [12]:
employees.sort_index(axis=1)

,Bonus %,First Name,Gender,Last Login Time,Salary,Senior Management,Start Date,Team
0,6.945,Douglas,Male,12:42 PM,97308,True,8/6/1993,Marketing
1,4.170,Thomas,Male,6:53 AM,61933,True,3/31/1996,None
2,11.858,Maria,Female,11:17 AM,130590,False,4/23/1993,Finance
3,9.340,Jerry,Male,1:00 PM,138705,True,3/4/2005,Finance
4,1.389,Larry,Male,4:47 PM,101004,True,1/24/1998,Client Services
...,...,...,...,...,...,...,...,...
995,16.655,Henry,None,6:09 AM,132483,False,11/23/2014,Distribution
996,19.675,Phillip,Male,6:30 AM,42392,False,1/31/1984,Finance
997,1.421,Russell,Male,12:39 PM,96914,False,5/20/2013,Product
998,11.985,Larry,Male,4:45 PM,60500,False,4/20/2013,Business Development
999,10.169,Albert,Male,6:24 PM,129949,True,5/15/2012,Sales

In [13]:
col_index = employees.axes[1]

In [14]:
sorted(col_index)

['Bonus %',
 'First Name',
 'Gender',
 'Last Login Time',
 'Salary',
 'Senior Management',
 'Start Date',
 'Team']

In [15]:
employees.sort_index(axis=1 , ascending=False)

,Team,Start Date,Senior Management,Salary,Last Login Time,Gender,First Name,Bonus %
0,Marketing,8/6/1993,True,97308,12:42 PM,Male,Douglas,6.945
1,None,3/31/1996,True,61933,6:53 AM,Male,Thomas,4.170
2,Finance,4/23/1993,False,130590,11:17 AM,Female,Maria,11.858
3,Finance,3/4/2005,True,138705,1:00 PM,Male,Jerry,9.340
4,Client Services,1/24/1998,True,101004,4:47 PM,Male,Larry,1.389
...,...,...,...,...,...,...,...,...
995,Distribution,11/23/2014,False,132483,6:09 AM,None,Henry,16.655
996,Finance,1/31/1984,False,42392,6:30 AM,Male,Phillip,19.675
997,Product,5/20/2013,False,96914,12:39 PM,Male,Russell,1.421
998,Business Development,4/20/2013,False,60500,4:45 PM,Male,Larry,11.985
999,Sales,5/15/2012,True,129949,6:24 PM,Male,Albert,10.169

In [16]:
 employees.sort_index(axis = 1,key=lambda c : c.str.len())

,Team,Gender,Salary,Bonus %,First Name,Start Date,Last Login Time,Senior Management
0,Marketing,Male,97308,6.945,Douglas,8/6/1993,12:42 PM,True
1,None,Male,61933,4.170,Thomas,3/31/1996,6:53 AM,True
2,Finance,Female,130590,11.858,Maria,4/23/1993,11:17 AM,False
3,Finance,Male,138705,9.340,Jerry,3/4/2005,1:00 PM,True
4,Client Services,Male,101004,1.389,Larry,1/24/1998,4:47 PM,True
...,...,...,...,...,...,...,...,...
995,Distribution,None,132483,16.655,Henry,11/23/2014,6:09 AM,False
996,Finance,Male,42392,19.675,Phillip,1/31/1984,6:30 AM,False
997,Product,Male,96914,1.421,Russell,5/20/2013,12:39 PM,False
998,Business Development,Male,60500,11.985,Larry,4/20/2013,4:45 PM,False
999,Sales,Male,129949,10.169,Albert,5/15/2012,6:24 PM,True

In [17]:
 employees.sort_index(axis = 1,key=lambda c : c.str.len(), ascending=False)

,Senior Management,Last Login Time,Start Date,First Name,Bonus %,Gender,Salary,Team
0,True,12:42 PM,8/6/1993,Douglas,6.945,Male,97308,Marketing
1,True,6:53 AM,3/31/1996,Thomas,4.170,Male,61933,None
2,False,11:17 AM,4/23/1993,Maria,11.858,Female,130590,Finance
3,True,1:00 PM,3/4/2005,Jerry,9.340,Male,138705,Finance
4,True,4:47 PM,1/24/1998,Larry,1.389,Male,101004,Client Services
...,...,...,...,...,...,...,...,...
995,False,6:09 AM,11/23/2014,Henry,16.655,None,132483,Distribution
996,False,6:30 AM,1/31/1984,Phillip,19.675,Male,42392,Finance
997,False,12:39 PM,5/20/2013,Russell,1.421,Male,96914,Product
998,False,4:45 PM,4/20/2013,Larry,11.985,Male,60500,Business Development
999,True,6:24 PM,5/15/2012,Albert,10.169,Male,129949,Sales

In [20]:
 employees.sort_index(axis = 0,key=lambda r : r % 10 == 1 , ascending=False)

,First Name,Gender,Start Date,Last Login Time,Salary,Bonus %,Senior Management,Team
291,Tammy,Female,11/11/1984,10:30 AM,132839,17.463,True,Client Services
341,Carlos,Male,9/19/2007,1:01 AM,77327,11.580,True,Finance
681,Frank,Male,11/23/2002,6:10 PM,75147,17.398,False,Product
431,Charles,Male,12/16/1999,8:28 PM,104014,7.077,False,Legal
611,Elizabeth,None,2/16/1981,3:58 AM,52730,12.525,False,Marketing
...,...,...,...,...,...,...,...,...
354,Elizabeth,Female,11/10/2005,4:56 AM,106406,1.782,True,Legal
355,Andrea,Female,9/14/2003,10:30 PM,115913,12.121,False,Legal
356,Judy,Female,2/1/1990,3:32 PM,38092,5.668,False,Distribution
357,Russell,Male,8/13/2014,3:51 PM,121160,7.843,False,Engineering
999,Albert,Male,5/15/2012,6:24 PM,129949,10.169,True,Sales