In [4]:
import pandas as pd
df = pd.DataFrame({
    'A':[1,2,None,4],
    'B':[None,3,4,None],
    'C':[5,None,None,6]
})

In [5]:
df

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  6.0

In [6]:
 df.isna()

       A      B      C
0  False   True  False
1  False  False   True
2   True  False   True
3  False   True  False

In [8]:
df

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  6.0

In [9]:
df.isna()

       A      B      C
0  False   True  False
1  False  False   True
2   True  False   True
3  False   True  False

In [10]:
df[df.isna()]

    A   B   C
0 NaN NaN NaN
1 NaN NaN NaN
2 NaN NaN NaN
3 NaN NaN NaN

In [11]:
df

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  6.0

In [12]:
df.isnull()

       A      B      C
0  False   True  False
1  False  False   True
2   True  False   True
3  False   True  False

In [13]:
df.notnull()

       A      B      C
0   True  False   True
1   True   True  False
2  False   True  False
3   True  False   True

In [14]:
df.notna()

       A      B      C
0   True  False   True
1   True   True  False
2  False   True  False
3   True  False   True

In [15]:
df.notnull()

       A      B      C
0   True  False   True
1   True   True  False
2  False   True  False
3   True  False   True

In [17]:
df.fillna(0)

     A    B    C
0  1.0  0.0  5.0
1  2.0  3.0  0.0
2  0.0  4.0  0.0
3  4.0  0.0  6.0

In [18]:
df

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  6.0

In [19]:
df.fillna("boared training")

                 A                B                C
0              1.0  boared training              5.0
1              2.0              3.0  boared training
2  boared training              4.0  boared training
3              4.0  boared training              6.0

In [20]:
df

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  6.0

In [21]:
df.ffill()

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  5.0
2  2.0  4.0  5.0
3  4.0  4.0  6.0

In [22]:
df

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  6.0

In [23]:
df.bfill()

     A    B    C
0  1.0  3.0  5.0
1  2.0  3.0  6.0
2  4.0  4.0  6.0
3  4.0  NaN  6.0

In [24]:
df.dropna()

Empty DataFrame
Columns: [A, B, C]
Index: []

In [25]:
df

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  6.0

In [26]:
df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3]

In [27]:
df.dropna(how='all')

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  6.0

In [28]:
df.dropna(how="any")

Empty DataFrame
Columns: [A, B, C]
Index: []

In [29]:
df

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  6.0

In [31]:
import pandas as pd
df = pd.DataFrame({
    'A':[1,2,None,4],
    'B':[None,3,4,None],
    'C':[5,None,None,None]
})

In [32]:
df

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  NaN

In [33]:
df.dropna(how='all')

     A    B    C
0  1.0  NaN  5.0
1  2.0  3.0  NaN
2  NaN  4.0  NaN
3  4.0  NaN  NaN

In [34]:
import pandas as pd
df = pd.DataFrame({
    'A':[None,None,None,None],
    'B':[None,3,4,None],
    'C':[5,None,None,None]
})

In [35]:
df

      A    B    C
0  None  NaN  5.0
1  None  3.0  NaN
2  None  4.0  NaN
3  None  NaN  NaN

In [40]:
df.dropna(how='all',axis=1)

     B    C
0  NaN  5.0
1  3.0  NaN
2  4.0  NaN
3  NaN  NaN

In [41]:
df.drop(columns=['C'])

      A    B
0  None  NaN
1  None  3.0
2  None  4.0
3  None  NaN

In [42]:
df

      A    B    C
0  None  NaN  5.0
1  None  3.0  NaN
2  None  4.0  NaN
3  None  NaN  NaN

In [43]:
df.drop(index=2)

      A    B    C
0  None  NaN  5.0
1  None  3.0  NaN
3  None  NaN  NaN

In [44]:
df =pd.DataFrame({
    'X':[1,1,2,3,4,4],
    'Y':[5,5,7,7,8,9]
})

In [45]:
df

   X  Y
0  1  5
1  1  5
2  2  7
3  3  7
4  4  8
5  4  9

In [47]:
df.drop_duplicates()

   X  Y
0  1  5
2  2  7
3  3  7
4  4  8
5  4  9

In [49]:
df.drop_duplicates(subset='X')

   X  Y
0  1  5
2  2  7
3  3  7
4  4  8