In [2]:
import pandas as pd

In [5]:
df1=pd.DataFrame({
    'A':[12,19,23],
    'B':[12,21,32],
})
df2=pd.DataFrame({
    'A':[111,None,232],
    'B':[None,212,None],
})

In [6]:
df1

    A   B
0  12  12
1  19  21
2  23  32

In [7]:
df2

       A      B
0  111.0    NaN
1    NaN  212.0
2  232.0    NaN

In [8]:
df1.update(df2)

In [9]:
df1

     A    B
0  111   12
1   19  212
2  232   32

In [10]:
df1=pd.DataFrame({
    'A':[12,19,23],
    'B':[12,21,32],
})
df2=pd.DataFrame({
    'A':[111,None,232],
    'B':[None,212,None],
})

In [11]:
df1.update(df2,filter_func=lambda x:x > 15)

In [20]:
df1=pd.DataFrame({
    'A':[11,19,23],
    'B':[12,21,32],
})
df2=pd.DataFrame({
    'A':[111,None,232],
    'B':[None,212,None],
})

In [21]:
 def update_on_condition(x): 
     return x > 21

In [22]:
df1.update(df2,filter_func=update_on_condition)

In [23]:
df1

     A   B
0   11  12
1   19  21
2  232  32

In [28]:
df1=pd.DataFrame({
    'A':[11,19,23],
    'B':[12,21,32]
},index=['a','b','c'])
df2=pd.DataFrame({
    'A':[111,232],
    'B':[212,222]
}, index=['b','c'])

In [29]:
df1

    A   B
a  11  12
b  19  21
c  23  32

In [30]:
df2

     A    B
b  111  212
c  232  222

In [33]:
df1.update(df2)

In [34]:
df1

     A    B
a   11   12
b  111  212
c  232  222

In [35]:
df2

     A    B
b  111  212
c  232  222

In [36]:
pd.concat([df1,df2])

     A    B
a   11   12
b  111  212
c  232  222
b  111  212
c  232  222

In [37]:
pd.concat([df1,df2], ignore_index= True)

     A    B
0   11   12
1  111  212
2  232  222
3  111  212
4  232  222

In [38]:
pd.concat([df1,df2], ignore_index= True ,axis=0)

     A    B
0   11   12
1  111  212
2  232  222
3  111  212
4  232  222

In [39]:
pd.concat([df1,df2], ignore_index= True ,axis=1)

     0    1      2      3
a   11   12    NaN    NaN
b  111  212  111.0  212.0
c  232  222  232.0  222.0

In [41]:
pd.concat([df1,df2], join='inner')

     A    B
a   11   12
b  111  212
c  232  222
b  111  212
c  232  222

In [42]:
df1=pd.DataFrame({
    'A':[11,19,23],
    'B':[12,21,32]
},index=['101','102','103'])
df2=pd.DataFrame({
    'A':[111,232],
    'B':[212,222]
}, index=['102','104'])

In [43]:
pd.concat([df1,df2], join='inner')

       A    B
101   11   12
102   19   21
103   23   32
102  111  212
104  232  222

In [44]:
pd.concat([df1,df2], join='inner' , axis=1)

      A   B    A    B
102  19  21  111  212

In [48]:
pd.concat([df1,df2], join='outer' )

       A    B
101   11   12
102   19   21
103   23   32
102  111  212
104  232  222

In [49]:
pd.concat([df1,df2], keys=['df1','df2'])

           A    B
df1 101   11   12
    102   19   21
    103   23   32
df2 102  111  212
    104  232  222

In [50]:
df1

      A   B
101  11  12
102  19  21
103  23  32

In [51]:
df2

       A    B
102  111  212
104  232  222

In [53]:
df1.combine(df2 , func = lambda x,y : x+y)

         A      B
101    NaN    NaN
102  130.0  233.0
103    NaN    NaN
104    NaN    NaN

In [54]:
df1.reset_index(drop=True , inplace=True)

In [55]:
df1

    A   B
0  11  12
1  19  21
2  23  32

In [56]:
df2

       A    B
102  111  212
104  232  222

In [57]:
df1.combine(df2 , func = lambda x,y : x+y)

      A   B
0   NaN NaN
1   NaN NaN
2   NaN NaN
102 NaN NaN
104 NaN NaN

In [58]:
df1.combine(df2 , func = lambda x,y : x+y , fill_value=0)

         A      B
0     11.0   12.0
1     19.0   21.0
2     23.0   32.0
102  111.0  212.0
104  232.0  222.0