In [1]:
import pandas as pd
from sqlalchemy import create_engine
# connection string
engine = create_engine(
    "postgresql+psycopg2://udemy:udemy123@localhost:5434/udemy_master_of_pandas"
)

# read table
employees = pd.read_sql("SELECT * FROM master.employees;", engine)

In [2]:
df1=pd.DataFrame(
    {
        'Name':['Yash','Rafid','John'],
        'Age':[25,30,35],
    },index=[101,102,103]
)

In [3]:
df2=pd.DataFrame(
    {
        'Salary':[55000,70000,9000],
    },index=[101,102,103]
)

In [4]:
df1

      Name  Age
101   Yash   25
102  Rafid   30
103   John   35

In [5]:
df2

     Salary
101   55000
102   70000
103    9000

In [6]:
df1.index

Index([101, 102, 103], dtype='int64')

In [7]:
df2.index

Index([101, 102, 103], dtype='int64')

In [8]:
df1.join(df2)

      Name  Age  Salary
101   Yash   25   55000
102  Rafid   30   70000
103   John   35    9000

In [9]:
df1

      Name  Age
101   Yash   25
102  Rafid   30
103   John   35

In [10]:
df1.join(df2, how='inner')

      Name  Age  Salary
101   Yash   25   55000
102  Rafid   30   70000
103   John   35    9000

In [11]:
df1

      Name  Age
101   Yash   25
102  Rafid   30
103   John   35

In [15]:
df2=pd.DataFrame(
    {
        'Salary':[55000,70000,9000],
    },index=[102,103,104]
)

In [13]:
df1

      Name  Age
101   Yash   25
102  Rafid   30
103   John   35

In [16]:
df2

     Salary
102   55000
103   70000
104    9000

In [17]:
df1.join(df2)

      Name  Age   Salary
101   Yash   25      NaN
102  Rafid   30  55000.0
103   John   35  70000.0

In [18]:
df1.join(df2,how='inner')

      Name  Age  Salary
102  Rafid   30   55000
103   John   35   70000

In [19]:
df1.join(df2,how='outer')

      Name   Age   Salary
101   Yash  25.0      NaN
102  Rafid  30.0  55000.0
103   John  35.0  70000.0
104    NaN   NaN   9000.0

In [20]:
df1.join(df2,how='left')

      Name  Age   Salary
101   Yash   25      NaN
102  Rafid   30  55000.0
103   John   35  70000.0

In [21]:
df1.join(df2,how='right')

      Name   Age  Salary
102  Rafid  30.0   55000
103   John  35.0   70000
104    NaN   NaN    9000

In [29]:
df1=pd.DataFrame(
    {
        'ID':[101,102,103],
        'Name':['Yash','Rafid','John'],
        'Age':[25,30,35],
    }
)
df2=pd.DataFrame(
    {
        'ID':[102,103,104],
        'Salary':[55000,70000,90000],
    }
)

df1

In [24]:
df1

    ID   Name  Age
0  101   Yash   25
1  102  Rafid   30
2  103   John   35

In [25]:
df2

    ID  Salary
0  101   55000
1  102   70000
2  103   90000

In [26]:
df1.index

RangeIndex(start=0, stop=3, step=1)

In [27]:
df2.index

RangeIndex(start=0, stop=3, step=1)

In [31]:
df1.set_index('ID').join(df2.set_index('ID'))

      Name  Age   Salary
ID
101   Yash   25      NaN
102  Rafid   30  55000.0
103   John   35  70000.0

In [32]:
df1.set_index('ID').join(df2.set_index('ID'),how='inner')

      Name  Age  Salary
ID
102  Rafid   30   55000
103   John   35   70000

In [33]:
df1.set_index('ID').join(df2.set_index('ID'),how='right')

      Name   Age  Salary
ID
102  Rafid  30.0   55000
103   John  35.0   70000
104    NaN   NaN   90000

In [34]:
df1.set_index('ID').join(df2.set_index('ID'),how='left')

      Name  Age   Salary
ID
101   Yash   25      NaN
102  Rafid   30  55000.0
103   John   35  70000.0

In [36]:
df1.set_index('ID').join(df2.set_index('ID'),how='outer')

      Name   Age   Salary
ID
101   Yash  25.0      NaN
102  Rafid  30.0  55000.0
103   John  35.0  70000.0
104    NaN   NaN  90000.0

In [37]:
df1.merge(df2,how='inner')

    ID   Name  Age  Salary
0  102  Rafid   30   55000
1  103   John   35   70000

In [38]:
df1

    ID   Name  Age
0  101   Yash   25
1  102  Rafid   30
2  103   John   35

In [39]:
df1.merge(df2,how='outer')

    ID   Name   Age   Salary
0  101   Yash  25.0      NaN
1  102  Rafid  30.0  55000.0
2  103   John  35.0  70000.0
3  104    NaN   NaN  90000.0